# Implementación el método de la máxima verosimilitud para la regresión logística

#### Fuente:
https://www.cienciadedatos.net/documentos/py17-regresion-logistica-python.html

https://www.cienciadedatos.net/documentos/27_regresion_logistica_simple_y_multiple



#### Otras fuentes:
https://medium.com/codex/logistic-regression-and-maximum-likelihood-estimation-function-5d8d998245f9

https://machinelearningmastery.com/logistic-regression-with-maximum-likelihood-estimation/


#### Maximum Likelihood Estimation / Estimador de máxima verosimilitud
https://faculty.washington.edu/ezivot/econ583/mleLectures.pdf


#### Statmodel
https://www.statsmodels.org/stable/discretemod.html


#### Sklearn
https://scikit-learn.org/0.16/modules/generated/sklearn.linear_model.LogisticRegression.html



Para tratar 



## Situación profesional Logistic Regression

Resolver las siguientes consignas:

1- Indicar la secuencia de pasos para resolver el algoritmo de regresión logística

2- La fórmula de la celda 1 ¿Es correcta? ¿Se corresponde con la función likelihood?
Revisar el anexo 2: https://www.cienciadedatos.net/documentos/py17-regresion-logistica-python.html

3- Modificar la matriz X e Y de la siguientes maneras (resolver con los 3 métodos:
    a- Simétricos los 0 y 1 de Y. Aquí aparecerá el mensaje de Sigular matrix https://stackoverflow.com/questions/13795682/numpy-error-singular-matrix 
    b- dejar un 1 y nueve 0
    c- repetir valores en X con distintos valores en Y (ej. x1=1 y1=0, x2=1 y2=1 ....) identificar que pasa con la precisión?. Aplicar otras métricas.
  
4- Agregar a X atributos (columnas) de manera que queden en total 3. Deben tener valores extremos. 

5- En el caso del algoritmo codificado con funciones ¿Cómo se realiza una predicción? 

6- Agregar LogisticRegression de Sklearn y resolver los puntos anteriores.

7- Investigar en ésta librería los métodos de ajuste de éste algoritmo ¿Cual método de ajuste usa el código cón funciones?

8- Identificar la zona de división de las categorías (esto es sobre valores del eje x, por ej, si para y=0 el máxomo valor es 3 y para y=1 el menor valor es 7) ¿Cual es el máximo para x de y=0 y el mínimo de x para y=1?

9- Repetir para 3 categorías, o sea: Y=1, Y=2 e Y=3.

10- Emitir un informe.




# RESPUESTAS

1- Indicar la secuencia de pasos para resolver el algoritmo de regresión logística

  Las etapas para resolver el algoritmo de regresion logistica son los siguientes:


  1.   Importar conjunto de datos.
  2.   Importar Librerias.
  3.   Análisis exploratorio de datos
    1. a - Listar columnas.
    2. b - Numero de Observaciones.
    3. c - Tipos de datos de las columnas.
    4. d - Separar entre tipos de Variables (Categoricas, Numericas)
    5. e - Valores faltantes en variables categóricas.
    6. f - Recuentos / Distribucion / Cardinalidad / de frecuencia de las variables categóricas.
    7. g - Normalizacion / Eliminar NAN
    8. h - Valores perdidos en **variables numéricas**
    9. i - Valores atípicos en **variables numéricas**
    10. j - Comprobar la distribución de variables. (graficos).
  4. Declarar vector de características y variable de destino
  5. Divida los datos en conjuntos de prueba y entrenamiento separados
  6. **Instanciar Modelo**
  7. Entrenar.
  8. Predecir.
  9. Evaluar Resultados. (METRICAS)
  10. Evaluar Supuestos para corregir y volver a entrenar y Predecir

2- La fórmula de la celda 1 ¿Es correcta? ¿Se corresponde con la función likelihood? Revisar el anexo 2: https://www.cienciadedatos.net/documentos/py17-regresion-logistica-python.html

R: **SI ES CORRECTA**

3- Modificar la matriz X e Y de la siguientes maneras (resolver con los 3 métodos: 
* a- Simétricos los 0 y 1 de Y. Aquí aparecerá el mensaje de Sigular matrix https://stackoverflow.com/questions/13795682/numpy-error-singular-matrix 
* b- dejar un 1 y nueve 0 
* c- repetir valores en X con distintos valores en Y (ej. x1=1 y1=0, x2=1 y2=1 ....) identificar que pasa con la precisión?. Aplicar otras métricas.

La metricas cambian, esto se debe a la disposicion de los tatos, ya que al modificar la matriz Y (salida) al momento de entrenar nuevamente el modelo modifica sustancialmente las metricas.
Lo mismo Sucede al modificar la matriz de input (X) ya que las variables cambian sus valores modificando las metricas del modelo.
**Si los datos modificados NO CUMPLE con los supuestos de la regresion logistica el modelo no podra correr**


4- Agregar a X atributos (columnas) de manera que queden en total 3. Deben tener valores extremos.

```
xa = np.random.uniform(low=8, high=10, size=10).reshape(10,1)

xb = np.random.uniform(low=0, high=3, size=10).reshape(10,1)

X_new = np.append(X,xa,axis=1)

X_new = np.append(X_new,xb,axis=1)

```








### Definir la función de entorno L(b)

In [1]:
from IPython.display import display, Math, Latex
display(Math(r'L(\beta)=\sum_{i=1}^n P_i^{y_i}(1-Pi)^{y_i}'))

<IPython.core.display.Math object>

In [2]:
def likelihood(y, pi):
    import numpy as np
    total_sum = 1
    sum_in = list(range(1, len(y)+1))
    for i in range(len(y)):
        sum_in[i] = np.where(y[i]==1, pi[i], 1-pi[i])
        total_sum = total_sum * sum_in[i]
    return total_sum

### Calcular las probabilidades para cada observación

In [3]:
display(Math(r'P_i = P(x_i) = \frac{1}{1+e^{-\sum_{j=0}^k\beta_j\cdot x_{ij}}} '))

<IPython.core.display.Math object>

In [4]:
def logitprobs(X,beta):
    import numpy as np
    n_rows = np.shape(X)[0]
    n_cols = np.shape(X)[1]
    pi=list(range(1,n_rows+1))
    expon=list(range(1,n_rows+1))
    for i in range(n_rows):
        expon[i] = 0
        for j in range(n_cols):
            ex=X[i][j] * beta[j]
            expon[i] = ex + expon[i]
        with np.errstate(divide="ignore", invalid="ignore"):
            pi[i]=1/(1+np.exp(-expon[i]))
    return pi

### Calcular la matriz diagonal W

In [5]:
display(Math(r'W= diag(P_i \cdot (1-P_i))_{i=1}^n'))

<IPython.core.display.Math object>

In [6]:
def findW(pi):
    import numpy as np
    n = len(pi)
    W = np.zeros(n*n).reshape(n,n)
    for i in range(n):
        print(i)
        W[i,i]=pi[i]*(1-pi[i])
        W[i,i].astype(float)
    return W

### Obtener la solución de la función logística

In [7]:
display(Math(r"\beta_{n+1} = \beta_n -\frac{f(\beta_n)}{f'(\beta_n)}"))
display(Math(r"f(\beta) = X(Y-P)"))
display(Math(r"f'(\beta) = XWX^T"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [8]:
def logistics(X, Y, limit):
    import numpy as np
    from numpy import linalg
    nrow = np.shape(X)[0]
    bias = np.ones(nrow).reshape(nrow,1)
    X_new = np.append(X, bias, axis = 1)
    ncol = np.shape(X_new)[1]
    beta = np.zeros(ncol).reshape(ncol,1)
    root_dif = np.array(range(1,ncol+1)).reshape(ncol,1)
    iter_i = 10000
    while(iter_i>limit):
        print("Iter:i"+str(iter_i) + ", limit:" + str(limit))
        pi = logitprobs(X_new, beta)
        print("Pi:"+str(pi))
        W = findW(pi)
        print("W:"+str(W))
        num = (np.transpose(np.matrix(X_new))*np.matrix(Y - np.transpose(pi)).transpose())
        den = (np.matrix(np.transpose(X_new))*np.matrix(W)*np.matrix(X_new))
        root_dif = np.array(linalg.inv(den)*num)
        beta = beta + root_dif
        print("Beta: "+str(beta))
        iter_i = np.sum(root_dif*root_dif)
        ll = likelihood(Y, pi)
    return beta

## Comprobación experimental

In [35]:
import numpy as np

In [42]:
X = np.array(range(10)).reshape(10,1)
#X= np.append(X,X,axis=1)

In [43]:
X

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [44]:
# Y = [0,0,0,0,1,0,1,0,1,1]
# Y = [0,0,0,0,0,0,0,0,0,1]
Y = [0,0,0,0,0,1,1,1,1,1]

In [45]:
bias = np.ones(10).reshape(10,1)
X_new = np.append(X,bias,axis=1)

In [46]:
# AGREGO COLUMNAS EXTREMAS

# xa = np.random.uniform(low=8, high=10, size=10).reshape(10,1)
# xb = np.random.uniform(low=0, high=3, size=10).reshape(10,1)
# X_new = np.append(X,xa,axis=1)
# X_new = np.append(X_new,xb,axis=1)

X_new

array([[0., 1.],
       [1., 1.],
       [2., 1.],
       [3., 1.],
       [4., 1.],
       [5., 1.],
       [6., 1.],
       [7., 1.],
       [8., 1.],
       [9., 1.]])

In [48]:
a = logistics(X,Y,1)

Iter:i10000, limit:1
Pi:[array([0.5]), array([0.5]), array([0.5]), array([0.5]), array([0.5]), array([0.5]), array([0.5]), array([0.5]), array([0.5]), array([0.5])]
0
1
2
3
4
5
6
7
8
9
W:[[0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.25 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.25 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.25 0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.25 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.25]]
Beta: [[ 0.60606061]
 [-2.72727273]]
Iter:i7.805325987144165, limit:1
Pi:[array([0.06138311]), array([0.10705215]), array([0.18017659]), array([0.2871859]), array([0.42481687]), array([0.57518313]), array([0.7128141]), array([0.81982341]), array([0.89294785]), array([0.93861689])]


In [49]:
ll = likelihood(Y, logitprobs(X,a))

In [50]:
ll

array([0.])

In [51]:
Y = 74.10217253 * X -334.45977638

# Con el paquete statsmodel de python

In [ ]:
import statsmodels.api as sm
import pandas as pd
from pandas import Timestamp

In [ ]:
Y = (Y - np.min(Y))/np.ptp(Y)
logit_model = sm.Logit(Y,X_new)

In [ ]:
result = logit_model.fit()

Optimization terminated successfully.
         Current function value: 0.359693
         Iterations 6


In [ ]:
print(result.summary2())

                         Results: Logit
Model:              Logit            Pseudo R-squared: 0.481    
Dependent Variable: y                AIC:              11.1939  
Date:               2022-02-26 11:26 BIC:              11.7990  
No. Observations:   10               Log-Likelihood:   -3.5969  
Df Model:           1                LL-Null:          -6.9315  
Df Residuals:       8                LLR p-value:      0.0098099
Converged:          1.0000           Scale:            1.0000   
No. Iterations:     6.0000                                      
------------------------------------------------------------------
           Coef.    Std.Err.      z      P>|z|     [0.025   0.975]
------------------------------------------------------------------
x1         0.6272     0.3735    1.6793   0.0931   -0.1048   1.3592
const     -2.8224     1.8730   -1.5069   0.1318   -6.4934   0.8485

